In [1]:
import tensorflow as tf

In [14]:
import numpy as np

In [3]:
td=tf.constant([
    [[1,2,0],
    [3,5,-1]],
    
    [[10,2,0],
    [1,0,2]],
    
    [[5,8,0],
    [2,7,0]],
    
    [[2,1,9],
    [4,-3,32]],
    
    
])

In [4]:
print(td)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [5]:
td

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0]],

       [[ 2,  1,  9],
        [ 4, -3, 32]]])>

In [6]:
td.shape

TensorShape([4, 2, 3])

In [10]:
on=tf.constant([2,0.],dtype=tf.int64)

TypeError: Cannot convert [2, 0.0] to EagerTensor of dtype int64

In [12]:
on=tf.constant([2,0.],dtype=tf.float64)
oncast=tf.cast(on,dtype=tf.int16)

In [16]:
arr=np.array([1,2,3])
tens=tf.convert_to_tensor(arr)

In [17]:
tens

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [25]:
et=tf.eye(
num_rows=3,
num_columns=None,
batch_shape=None,
dtype=tf.float32,
name=None)

In [24]:
et

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [30]:
asa=tf.fill([2,3],6,name='asaaa')

In [31]:
asa

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[6, 6, 6],
       [6, 6, 6]])>

In [34]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [53]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=1))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([0 1 3], shape=(3,), dtype=int32)


In [58]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32))

tf.Tensor([0 1 3], shape=(3,), dtype=int32)


In [59]:
ten=tf.constant([1,2,3,4,6,5,7])

In [60]:
ten[0:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [61]:
ten=tf.constant([[1,2,3,4,6,5,7],
               [1,2,3,4,6,5,7],
               [1,2,3,4,6,5,7]])

In [62]:
ten[0:2,:]

<tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 2, 3, 4, 6, 5, 7],
       [1, 2, 3, 4, 6, 5, 7]])>

In [63]:
var=tf.constant([1.2,-0.332])

In [64]:
ff=tf.abs(var)

In [65]:
ff

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2  , 0.332], dtype=float32)>

In [66]:
df=tf.math.abs(var)

In [67]:
df

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2  , 0.332], dtype=float32)>

In [68]:
print(df)

tf.Tensor([1.2   0.332], shape=(2,), dtype=float32)


In [69]:
tf.expand_dims(df,axis=1)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.2  ],
       [0.332]], dtype=float32)>

In [70]:
df=tf.constant([1,2,3])
print(tf.expand_dims(df,axis=1))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
