In [1]:
import tensorflow as tf
import numpy as np

In [4]:
para=tf.constant(['p0','p1','p2','p3','p4'])
para[2]

<tf.Tensor: shape=(), dtype=string, numpy=b'p2'>

In [5]:
para=tf.constant([1,2,3,4,5])
para[2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
params=tf.constant([[0,1.0,2.0],
                   [10.0,11.0,12.0],
                   [20,21,22],
                   [30.0,31.0,32.0]])

In [8]:
tf.gather(params,[2,1])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[20., 21., 22.],
       [10., 11., 12.]], dtype=float32)>

In [11]:
params=tf.constant([['a','b'],
                   ['c','d'],
                   ['e','f']])
indices=[2,1]
tf.gather_nd(params,indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [10]:
tf.gather(params,indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'e', b'f'],
       [b'c', b'd']], dtype=object)>

In [12]:
tfs=[[1,2,3],
     [3,],
     [1,3,5,6,5],
     [2,3]]
teen=tf.ragged.constant(tfs)
print(teen)

<tf.RaggedTensor [[1, 2, 3], [3], [1, 3, 5, 6, 5], [2, 3]]>


In [13]:
teen.shape

TensorShape([4, None])

In [14]:
type(tfs)

list

In [2]:
tf_sp=tf.sparse.SparseTensor(
indices=[[1,1],[3,4]],values=[11,56],dense_shape=[5,6])

In [3]:
print(tf_sp)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [4]:
tf.sparse.to_dense(tf_sp)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

In [5]:
x=tf.constant([1,2])
x_var=tf.Variable(x)
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
