In [1]:
import numpy as np


matrix = np.random.randint(0, 11, size=(5, 5))
print(matrix)

[[ 5  7  5  5  9]
 [ 1  6  0  6  0]
 [ 4  5  7  9  3]
 [ 5  9  4  1  4]
 [10  4  3  2  8]]


In [3]:
matrix = np.random.randn(3, 3)
print(matrix)

[[-0.64023589 -0.64541077 -0.20457958]
 [-0.13603701 -0.88320795 -0.04229659]
 [ 0.54041831 -1.54853082  2.01508441]]


In [4]:
matrix1 = np.random.randint(0, 10, size=(3, 3))
matrix2 = np.random.randint(0, 10, size=(3, 3))
result = matrix1 @ matrix2
print(result)


[[102  68  54]
 [ 12   6  50]
 [ 35   5  50]]


In [6]:
matrix = np.random.randint(0, 10, size=(3, 3))
tmatrix = matrix.T
print(matrix)
print(tmatrix)


[[4 9 4]
 [2 0 8]
 [2 2 5]]
[[4 2 2]
 [9 0 2]
 [4 8 5]]


In [8]:

array = np.random.randint(0, 100, size=10)
print(array)
sorted_indices = np.argsort(array)
print(sorted_indices)
sorted_array = array[sorted_indices]
print(sorted_array)


[30 95 56 95 46 23 14  6 63 48]
[7 6 5 0 4 9 2 8 1 3]

Sorted Array:
[ 6 14 23 30 46 48 56 63 95 95]


In [12]:
a=np.array([[11,22,33],[44,55,66],[77,88,99]])
result = a[:, 2]
result

array([33, 66, 99])

In [13]:
arrayOne=np.array([[5,6,9],[21,18,27]])
arrayTwo=np.array([[15,33,24],[4,7,1]])

summ=arrayOne+arrayTwo
print(summ)
summ**2

In [4]:
arrayOne=np.array([[5,6,9],[21,18,27]])
print(arrayOne.ndim)
print(arrayOne.size)
print(arrayOne.shape)
print(arrayOne.itemsize)
print(arrayOne.data)

2
6
(2, 3)
4


In [5]:
c=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])

In [7]:
c

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [8]:
c[0:5:2,1:5:2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [11]:
x=np.arange(10,34)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [12]:
s=x.reshape(8,3)

print(s)

In [15]:
ss=np.split(s,4)

In [16]:
ss

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [35]:
sam=np.array([[2,5,1],[6,7,2],[1,5,2]])
print(sam)

sa=sam[1,sam[1,:].argsort()]
print('\n',sa)

[[2 5 1]
 [6 7 2]
 [1 5 2]]

 [2 6 7]


In [36]:
sam=np.array([[2,5,1],[6,7,2],[1,5,2]])

In [37]:
print(np.amax(sam,0))

[6 7 2]


In [23]:
print(np.amin(sam,1))

[1 2 1]


In [30]:
print(sam,'\n')

sam[:,1]=np.array([3,4,5])
sam

[[2 5 1]
 [6 7 2]
 [1 5 2]] 



array([[2, 3, 1],
       [6, 4, 2],
       [1, 5, 2]])

In [34]:
print(sam)
delt=np.delete(sam,1,axis=1)
delt
nc=np.array([[2,3,1]])
ins=np.insert(delt,1,nc,axis=1)
print('\n',ins)
print('\n',sam)

[[2 3 1]
 [6 4 2]
 [1 5 2]]

 [[2 2 1]
 [6 3 2]
 [1 1 2]]

 [[2 3 1]
 [6 4 2]
 [1 5 2]]
